### ISSUE TITLE
INVERSIONISTA PR.3.0.1.Back: Usuario tiene la habilidad de confirmar email luego de Registrarse

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#10]
Como **_Usuario invitado_**, tengo la habilidad de registrarme como Inversionista.
Para lo cual, ya ingrese los datos de registro, y me debera llegar a mi email de confirmacion.

El contenido del email es el siguiente: 
Aqui llenar @fcobrionesr @cmatuteec 
```
Estimado {{nombre}}

¡Gracias por registrarte como inversionista en Crece Ecuador!

Descubre oportunidades de inversión en los términos que más se acoplen a tus preferencias. Explora las opciones en Oportunidades de Inversión y empieza a ganar rentabilidad con impacto social.

Si tienes dudas o deseas nuestro acompañamiento no dudes en contactarnos.

El equipo de Crece
```
Las credenciales del correo de crece Ecuador son las siguientes: @cmatuteec 
```
usuario: info@creceecuador.com
password: crece01GYE
```

MODELOS A AFECTAR:
Update usuario set estado=1 where id= 'ID_USUARIO'

```
**usuario**  (Solicitante/Inversionista)
______________________________
id (INT-autoincrement) PK
nombres VARCHAR(200)  NOT NULL
apellidos VARCHAR(200) NOT NULL
usuario VARCHAR(20) NOT NULL
password: VARCHAR(20) NOT NULL
email: VARCHAR(100) NOT NULL
celular: VARCHAR(20) NOT NULL
tipo_persona:  INTEGER (1=natural, 0 juridica)
direccion1: TEXT
direccion2: TEXT
ciudad: VARCHAR(25)
provincia: VARCHAR(25)
pais: VARCHAR(25)
```

**ENDPOINT:** **PUT inversionista/confirmar_email/**
**input:** Token
**Output:**
```
Response: 200
{
    mensaje: "Su Usuario ha sido confirmado con exito"
}
```
VER este tutorial. 
https://medium.com/@frfahim/django-registration-with-confirmation-email-bb5da011e4ef

**Comment by fcobrionesr** [comment]
No entiendo muy bien dónde debo hacer lo que me piden pero lo haré aquí:

¡Gracias por registrarte como inversionista en Crece Ecuador!

Descubre oportunidades de inversión en los términos que más se acoplen a tus preferencias. Explora las opciones en [Oportunidades de Inversión](https://www.creceecuador.com/oportunidades-de-inversion) y empieza a ganar rentabilidad con impacto social.

Si tienes dudas o deseas nuestro acompañamiento no dudes en contactarnos.

El equipo de Crece

**Comment by bram70** [comment]
@fcobrionesr Le das click en Editar al Contenido del issue, y escribes el contenido que se necesita.
