### ISSUE TITLE
Pantalla de Registro. Pantalla #2

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#109]
Aquí la mejora sería poner los campos tal como se muestra la pantalla, mas anchos y altos, y con los labels en la parte superior.
Tomar como referencia el ejemplo de la imagen adjunta, no quiere decir que se debe copiar textual el ejemplo.

![Screen Shot 2020-07-03 at 21 40 56](https://user-images.githubusercontent.com/550702/86503696-112a5900-bd76-11ea-9453-46995d1db744.png)

-> Adicionalmente agregar el campo de confirmacion de password .
 -> Añadir validación de cédula ecuatoriana. Ver enlace de referencia 
https://gist.github.com/vickoman/7800717

Para seguir mejorando la experiencia, en lugar de Registro añadir el siguiente título: ¡Estás a solo unos pasos de convertirte en un inversionista CRECE!

Hagamos verificación campo por campo del registro para indicarle al usuario qué campo debe corregir en caso de algún error. Recordar que no podemos exigir los dos nombres y los dos apellidos, solo un nombre y un apellido y con eso completar la firma de los contratos al dar clic en Resgistrarse. Este es un ejemplo, se puede indicar donde está el error con asteriscos, banderines, o como sea sencillo y tenga buena apariencia.
![image](https://user-images.githubusercontent.com/61850215/86638200-7eb7ce80-bf9c-11ea-905f-519d909ad62f.png)

Pongamos las preguntas de la encuesta en una sola columna. Las preguntas en una sola línea en la vista de PC.

Cambiemos las opciones de la pregunta:
¿Qué nivel de riesgo se ajusta a tu perfil?
- Medio
- Alto 
- Altísimo

Luego del registro se debe asignar un estado al inversionista. Los estados son:
- Confirmado 
- No confirmado
- Bloqueado
Asignar a todos el estado "No confirmado" y habilitar en la vista de operador la opción para cambiar el estado.

Añadir bajo botón un link al log in con el texto "¿Estás registrado? Inicia sesión aquí"

Si tienes dudas @luiggisao1 conversalo con @cmatuteec

**Comment by fcobrionesr** [comment]
Comentarios:

- Cambiar "Registro" por "Crear cuenta de inversionista"
- Validar campo cédula: limitar caracteres a 10 números
- Validar campo correo: no debe dejarme ingresar nada sin @algo
- Agregar campo de comprobación de contraseña con validación automática.
- Validar campo cédula: limitar caracteres a 10 números. Que empiece con 0.
- Ciudad: agregar más ciudades o la palabra "otra" que active casillero para poner nombre ciudad.
- Modificar: ¿En cuánto tiempo preferirías recuperar tus inversiones?
- ¿Qué nivel de riesgo prefieres más?
- ¿Cuánto capital deseas invertir a través de CRECE?
- No estoy seguro en preguntar cómo conociste a CRECE.
- Fuente más pequeña en declaración de aceptación de términos.
