### ISSUE TITLE
Pantalla de registro/check email. Pantalla #3

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#110]
En esta parte se puede mejorar agregando un icono de email, y la hora en que fue enviado el email. (timestamp, hora de Ecuador), y encerrando el mensaje en una caja blanca, y el fondo seria el mismo gris como en la pantalla de login.
En la caja blanca se debe poner el texto, explicando los siguientes pasos a realizar. Se puede tomar esta imagen, como referencia, mas no debe ser exactamente igual. "Hemos enviado un correo electrónico de verificación. Confirma tu dirección de correo y comienza a invertir."

<img width="968" alt="Screen Shot 2020-07-03 at 21 38 02" src="https://user-images.githubusercontent.com/550702/86503738-741bf000-bd76-11ea-8097-27b715841952.png">

Adicionalmente remover el footer de las paginas login, y registro, y dejar solo el cuadro blanco, con las redes en la parte inferior de dicho blanco, incluyendo los siguientes iconos y la parte de masinformacion, whatsapp, escribenos

<img width="482" alt="Screen Shot 2020-07-24 at 20 35 55" src="https://user-images.githubusercontent.com/550702/88446153-4feb8600-cded-11ea-8571-6d28f0b55e85.png">

![Screen Shot 2020-07-24 at 20 29 29](https://user-images.githubusercontent.com/550702/88446074-a2787280-cdec-11ea-83f0-29b359d64cf0.png)

Si tienes alguna duda @luiggisao1 consultar con @cmatuteec

**Comment by fcobrionesr** [comment]
Cambiar Registro por "Por favor activa tú cuenta"
Cambiar mensaje: Gracias por registrarte en CRECE. Por favor activa tu cuenta desde el enlance que enviamos a tu correo electrónico.
