### ISSUE TITLE
Mejoras - 2do round - Luiggi

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#146]
- [x] En la ventana de ver mas dentro del dashboard, ya no se debe mostrar CREAR USUARIO, INVERTIR, porque ya esta dentro del dashboard

- [x] Cuando se da click a ver mas, se queda el layout ahi, y luego le das click a cualquier otra opcion y no se mueve.

- [x] Si en alguna tarjeta ya esta como pendiente, y el usuario le vuelve a dar click a invertir, le debe redireccionar a la tarjeta que esta pendiente. Esto es una validacion antes de iniciar un nuevo proceso, se debe consultar en la base de datos, si existe una inversion con el ID INVERSION y el ID USUARIO. Si existe redireccionarlo al estado en el que se encuentre.

- [x] Dejar el acordeon del menu de "Mis inversiones" abierto.

- [x] En la lista de oportunidades, si ya la tarjeta ha disparado el trámite de inversión, y está pendiente de transferir, cambiar el boton de "invertir", por "continuar" y agregarle un distintivo en la esquina superior izquierda. Ver imagen. 

~~@bram70 **¿A qué te refieres con que ya ha sido invertida? ¿Que se ha completado la cantidad solicitada o que el inversionista ha invertido en esa solicitud? Si es el segundo caso no se debería bloquear el botón invertir, el inversionista puede volver a invertir en la misma solicitud respetando que no puede invertir más del 90% del total solicitado.**~~
Respuesta: Si es que ya está en trámite, (En algún estado antes de la transferencia)
 
![Screen Shot 2020-08-25 at 14 51 17](https://user-images.githubusercontent.com/550702/91220987-a0068280-e6e2-11ea-862c-f15b02b020aa.png)

- [x] En el formulario de completar datos del inversionista, escribir "Nombres:", (cambiar a plural).

- [x] Asignar a Titular de la cuenta bancaria los nombres y apellidos automáticamente y deshabilitar la posibilidad de editar ese campo. No se permite ingresar una cuenta donde el usuario no sea el titular.

- [x] En el listado de ciudades deben aparecer todos los cantones ordenados alfabéticamente. O cambiar el campo para que se permita escribir y se autocompleta el texto con los datos de los cantones, de tal forma que aunque se pueda escribir solo se pueda ingresar el nombre de un cantón de la lista.

- [x] Cambiar título de campo "Ingresos aproximados" por "Ingresos mensuales aproximados".

- [x] Cuando se selecciona Profesional independiente, en el campo de RUC copiar el número de cédula y añadir al final 001 y bloquear la posibilidad de editar.

- [ ] Cuando el usuario esté en la versión para móvil y toque en cargar documento de la cédula, habilitar posibilidad de tomar foto. En ese caso permitir cargar dos archivos porque tomará una foto para cada lado del documento.

- [x] Cuando el usuario haya iniciado sesión y se dirija a la página principal de CRECE, cambiar botón "Ingresar" ubicado en la esquina superior derecha por "Mi cuenta".

- [x] Cambiar "Historial de inversiones" por "Calendario de pagos"

- [x] En paso 3 declaración de origen de fondos cambiar última frase por:  "Los datos aquí consignados obedecen a la realidad. Al dar clic en Siguiente declaro (amos) haber leído, entendido y aceptado libremente el presente documento.".

- [x] Guardar la declaración de origen de fondos en un archivo PDF para ser mostrada en la sección de contratos aceptados en el perfil del usuario junto a la fecha y hora de aceptación.

- [x] En la pantalla de cargar comprobante de transferencia, la línea de "A nombre de:" debe presentar el nombre del solicitante, no del inversionista.

- [x] Cambiar el número de "Teléfono:" por 0988349088

- [x] Los compromisos que hayan pasado de "Waiting to be fund" a "Valid" deben presentar un solo botón que diga "Ver tabla" donde se presentará la tabla guardada en un modal, similar a la pantalla de confirmar cantidad da invertir sin la opción de ingresar una cantidad y sin el botón de Simular. La tabla debe añadir una columna más que es la fecha de pago. La fecha de pago de cada cuota se calcula a partir de la fecha de finalización como lo hablamos con Luiggi.

**Comment by cmatuteec** [comment]
@bram70 como clasificaremos los compromisos de inversión? Tendrán un ID? Cómo pasan de "Pending to send transfer" a "Waiting to be fund" y luego a "Valid"?
