### ISSUE TITLE
RI.1.0.1.Frontend Inversionista registra datos personales y financieros para inversión

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#17]
Una vez registrado el usuario como **Inversionista**, el usuario decide dar clic sobre invertir en una oportunidad de inversión, y luego de lo cual, es redireccionando a una ventana donde inicia el proceso de registro para dicha oportunidad de inversión.
El primer paso del registro es completar su información que se guardará en su perfil de usuario. Los primeros dos campos se muestran según la info recopilada en el registro. El formulario será dinámico y desplegará nuevas preguntas según aplique. La información solicitada será la siguiente:

Para lo cual se debera hacer las siguiente modificaciones/ingreso de nuevos modelos:

```
**inversionista:**
cedula: NULL,
cedula_ruta: TEXT, NULL
conyuge_id : NULL
telefono_domicilio: VARCHAR(30), NULL
ingresos: INT (FK) NULL
cuenta_bancaria: INT (FK) NULL
___________________

**conyuge**
id: INT PK
nombres: VARCHAR(100)
apellidos: VARCHAR(100)
cedula: VARCHAR(20) 
___________________

**fuente_ingresos**
id: INT AUTOINCREMENT PK
descripcion: TEXT, (objeto JSON con la descripcion, i.e. 
"{empresa: "MICOMISARIATO",
cargo: "GERENTE DE VENTAS", 
numero_anios:  4 }"

direccion: VARCHAR(200)
ciudad: VARCHAR(50)
ingresos_mensuales: decimal(10,2)
___________________
**banco:**
id: INT AUTOINCREMENT PK 
nombre: VARCHAR(150)

___________________
**cuenta_bancaria**
id INT AUTOINCREMENT PK
banco:  id FK a banco,
numero_cuenta: VARCHAR(15)
tipo_cuenta:  integer (0=ahorros,1=corriente)
estado: VARCHAR(50) , POR_VERIFICAR, VERIFICADA
```

```
Nombres _____
Apellidos _____
Cédula _____
Celular _____
Cónyuge Si__ No __
(si selecciona Si se despliegan las siguientes 3 preguntas)
Nombres ____
Apellidos ____
No de cédula ____

Dirección de domicilio ____
Ciudad ____
Provincia ____
Teléfono de domicilio ____

Principal fuente de ingresos
•	Relación de dependencia
•	Profesional independiente
•	Auto empleado

(Si selecciona Relación de dependencia, completar)
Empresa ___
Cargo ___
Años en el puesto ___

(Si selecciona profesional independiente, completar)
RUC ___
Actividad ___
Años en la actividad ___

(Si selecciona auto empleado, completar)
Empresa ___
RUC ___
Actividades ___

Dirección ___
Ciudad ___
Ingresos mensuales aprox. ___

Registra tu cuenta bancaria donde recibirás tus ganancias
Banco (lista desplegable)
No de cuenta
Tipo de cuenta Ahorros __ Corriente __
```
![inversionista_paso1](https://user-images.githubusercontent.com/61850215/76725173-6127d600-671b-11ea-9a2c-ba2aa9c99a7e.jpg)

Luego de completar el formulario, el usuario tendrá dos opciones. Dar clic en **Guardar** para guardar los datos hasta ahora completados y continuar en otro momento. La otra opción será **Siguiente** para continuar a la siguiente pantalla que será confirmar la cantidad a invertir.

**Comment by fcobrionesr** [comment]
Esto de aquí también conoce el detalle operativo Cristóbal. Pero me parece que todo esto lo hablamos en su momento cuando hicimos los dibujos en pizarra. No trabajemos doble.
