### ISSUE TITLE
RI.2.0.1.Frontend	Inversionista registra información de la inversión

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#18]
Una vez registrado el usuario como **"Inversionista"**, el usuario inversionista decide dar click sobre invertir en una oportunidad de inversión, y luego de lo cual, es redireccionando a una ventana donde inicia el proceso de registro para dicha oportunidad de inversión.

Como **Segundo paso**, debe _**confirmar su inversión**_, para cual le serán presentada la tabla de la simulación antes realizada. La diferencia será que al final de la tabla el usuario tendrá tres opciones:
Dar clic en _**Guardar**_ la tabla generada y el proceso previo completado
Dar clic en _**Siguiente**_ para pasar a la pantalla a continuación
Dar clic en _**Descargar tabla**_ para guardarla en su dispositivo

![inversionista_confirma_inversion](https://user-images.githubusercontent.com/61850215/76727762-eebaf400-6722-11ea-9d49-0e3ac06017b6.jpg)

Para lo cual se necesita, ingresar la informacion de la inversion.
Modelo: 
```
**inversion:**
id PK INT AUTOINCREMENT
id_user INT FK User (Inversionista)
id_solicitud INT FK Solicitud
monto decimal(10,2)
adjudicacion decimal(5,2)
inversion_total decimal(10,2)
ganancia_total decimal(10,2)
estado (default 0=por confirmar, 1=confirmada)
______________________

**pago_detalle:**
id PK INT AUTOINCREMENT
id_inversion INT FK inversion
orden: integer,
fecha: date
pago: decimal(10,2)
comision: decimal(10,2)
comision_iva decimal(10,2)
ganancia decimal(10,2)
estado, integer (0=pendiente, 1=pagado, -1= retrasado)
```
Endpoint: registro/fase2
Metodo : POST
Authentication: Basic Auth
Body: 
{
   inversion: {
    monto: 1400.23,
    id_user: 1423,
    id_solicitud: 1325,
    adjudicacion: 16.00
    adjudicacion_iva: 1.92,
    inversion_total: 2017.92,
    ganancia_total: 2221.10
  }, 
  pagos: 
[
{ orden:1,
   fecha: "01/05/2020",
   pago: 227.86,
   comision: 9.00,
    comision_iva: 1.08,
     ganancia: 217.787
}, ....
]
}

**Comment by fcobrionesr** [comment]
Lo mismo, Cristóbal tiene los detalles operativos.
