### ISSUE TITLE
RI.3.0.Frontend	Inversionista firma contrato de inversión

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#19]
ANTECEDENTE: el usuario inversionista debe dar clic sobre invertir en una oportunidad de inversión, y luego de lo cual, es redireccionando a una ventana donde inicia el proceso de registro para dicha oportunidad de inversión.

Como paso final para el registro de "Inversionista", en la ventana de registro, debe agregar el checkbox de Aceptacion de contrato tal como se muestra en la imagen:

En esta pantalla el usuario podrá realizar 4 acciones:
1. Aceptar el contrato, al listar el checkbox.
2. URL click para ver el contrato PDF.
3. El evento de check en el checkbox, debera habilitar el boton de registro del usuario inversionista.

![firma de contrato](https://user-images.githubusercontent.com/550702/85081904-fe6b2e00-b192-11ea-9488-165af81f64e6.jpeg)

Nota: Se necesita registrar para consultas futuros que este usuario, usando sus credenciales, aceptó el contrato.

**Comment by fcobrionesr** [comment]
Esto es algo que lo conoce en detalle Cristóbal, no yo. O Roberto, el abogado.
