### ISSUE TITLE
Comentarios WEB

### ISSUE THREAD

**Issue by fcobrionesr** [bram70/viewflow-crece#67]
En el Header:
- [ ] Conócenos lleva tilde.
- [ ] Contáctanos en lugar de Contactos.
- [ ] Invierte en lugar de oportunidades.
- [ ] Se debería agregar uno que diga Financiamiento que lleve a la parte de solicitud de crédito.
- [ ] Debe mostrar los FAQ.

En galería de fotos:
- [ ] Ajustar tiempo de transición automática.

En banner sobre Crece:
- [ ] Primera oración en negrita.
- [ ] En segunda oración agregar: Ponemos en contacto a pequeños y medianos emprendedores *que necesitan financiamiento* con inversionistas que conceden los recursos.
- [ ] En cuarta oración en lugar "del papeleo" poner "de hacerlo posible".

En banner calculadoras:
- [ ] Tamaño es diferente. La altura del banner cambia al swithchear entre Solicitar e Invertir.
- [ ] Cuidar que alineación de textos sea la misma. Los textos en Solicitar están más arriba que los de Invertir.
- [ ] Ponerle numeración para que se entienda que es un proceso. 1, 2, 3 y 4. En formato "1."
- [ ] En calculadoras hacer bordes redondeados, según patrón de todo en la página.

En calculadoras Solicitar:

- [ ] Quitar borde. Definir un solo color para fondo y borde. Bordes redondeados.
- [ ] Agregar temporalidad a Tasa. Anual me parece que es.
- [ ] Hay un astericos con cuota mensual que no aparece por ningún lado.
- [ ] Agregar dos puntos (:) luego de Capital, Plazo, Tasa anual.
- [ ] Agregar arriba de capital a manera de instrucción la frase: Desliza los botones en las barras acorde a tu necesidad.
- [ ] Los botones (círuculos verdes) deben ser más pequeños.
- [ ] Los valores monetarios deben usar comas como separadores de miles.
- [ ] Todos los rectangulos (text boxes, botones) deben tener contornos redondeados.
- [ ] Cuidar que tamaño de fuente sea conforme al resto del sitio.
- [ ] 

En calculadorea Invertir:
- [ ] Mismos comentarios de forma que la otra calculadora.
- [ ] No funciona el cuadro comparativo inversion CRECE y BANCO.
- [ ] Orden debería ser: Capital, Plazo, Cuadro de texto con: "Rendimiento promedio anual (TIR) de operaciones CRECE:" + valor de la tasa (16.62%), Pago mensual.
- [ ] Coincido con JJ sobre lo que se debe mostrar en el cuadro comparativo.

_TIP:¿Es posible cambiar los colores de fondo y botón grande de Invertir al cambiar entre calculadoras? Eso ayudaría a la diferenciación. Pudiera ser por ejemplo inverir los colores. Cuando está en solicitar hay un color para el fondo del banner y otro para la calculadora. Al cambiar a Invertir se invierten estos colores, el del fondo va a la calculadora y el de la calculadora al fondo._

En el banner oportunidades de inversion:
- [ ] Poner signos de miles (,) a todos los valores.
- [ ] Botón ver más del banner es demasiado grande. No guarda proporción con el título del banner, por ejemplo.
- [ ] En tarjeta debe corregirse oración de recolección por: $2,760 (23%) recolectados.
- [ ] La descripción de JF en Crece debe ser color más opaco (menos relevante).

En página Conócenos
- [ ] Hay un banner vacío. Poner slider.
- [ ] Borrar 100% en todos los pilares.
- [ ] Sigamos idea de pilares poniendo los 4 en 4 columnas en una sola fila.

En el footer:
- [ ] Corregir faltas ortográficas.

**Comment by fcobrionesr** [comment]
Comentarios JJ.
Pagina principal
- La marquesina no se mueve automáticamente. Debería tener un flujo natural, sino se queda en el caso de Conto.
- En las 3 imágenes de la marquesina deberíamos decir a tipo de testimonial en pequeño quienes son, a qué actividad se dedican y qué edad tienen. 
- El logo blanco se ve como extraño. Debería ser completamente blanco.
- Uniformidad de letras. En la calculadora para solicitar estamos usando otra cosa. 
- Esta comparación que hacemos con el banco debería ser solo sobre los intereses. Para que sepan que la rentabilidad es casi 2 veces más.
- PROSPERAECU SA es unido, no hay espacio entre PROSPERA y ECU. Hay un error ortográfico en “nanciacion”
- Redes sociales logos. Me da la impresión de que no está alineado esto. El logo de Twitter está muy arriba. Otra cosa importante seria poner en orden de cual es el que mas usamos. No creo que sea Facebook, o si?

Pagina Nosotros:
- En la sección de mi equipo, sugiero hacer hipervínculos con LinkedIn. Eso teníamos antes y creo que le da un nice touch a la página y a Crece. Abrazamos la tecnología.
- Pilares. Revisemos que los colores siguen alguna lógica. En esta sección de nosotros hay un champú de verdes.

Página Oportunidades:
- En la medida que sea posible esto debería tener algunos Sorting:
- Recientes (orden por fecha de publicación)
- Hot (orden que nosotros elegimos)
- Rentabilidad (el que tiene el TIR mas alto, al mas bajo)
- Generación de empleo (los que generan mas empleo del mas alto al mas bajo)
- Cerca de finalizar (los que ya están por cerrar el proceso de recepción de fondos) – talvez este debería ser el default.

- Asimismo, podemos pensar en filtros:
- Actividad económica
- Ubicación (provincia o ciudades)
- etc

**Comment by fcobrionesr** [comment]
Comentarios versión móvil. MotoG5 - Chrome - Android.

- [ ] Todo en general está muy grande. Las fuentes y las secciones. Deberían ser más pequeñas en términos generales.
- [ ] La infografía no es la correcta, no se entiende. Creo que podría quedar mejor si la conserva igual que en la versión de escritorio aunque se vea más pequeña.
- [ ] El mayor problema se observa en las calculadoras que se sale el texto del cuadrado.

**Comment by cmatuteec** [comment]
Nuevos comentarios que considero importantes:

- Eliminar del menú superior la pestaña de "Contacto" con una pestaña de preguntas "Frecuentes" o "Cómo funciona", en el pie de página ya se indica info de contacto. Para esta versión, diría reemplazarla por "Preguntas frecuentes".
- Disminuir tiempo entre imágenes del banner.
- Añadir a imágenes de los premios el link de cada publicación en páginas web:
Digital Bank: (http://www.digitalbankla.com/noticias/crece-ecuador-es-la-startup-ganadora-del-digital-guayaquil/)
Ekos Summit: https://www.ekosnegocios.com/articulo/el-startup-summit-fue-el-evento-que-promovio-el-desarrollo-del-ecosistema-emprendedor-del-pais
- Homologar tipo de letra d ela página Montserrart y usar sus variantes.
- Adecuar el ancho de la página. En resoluciones de 1920x1080 aparece barra de desplazamiento horizontal y la barra de menú queda corta
![IMG_2658](https://user-images.githubusercontent.com/61850215/82108147-2bd73e80-96f2-11ea-8676-417deec4ec41.PNG)

Calculadora inversionista
- Cambiar palabra "Capital" por "Invertir"

**Comment by cmatuteec** [comment]
Vista en iPad 5ta generación buscador Safari vista horizontal

- Apilamiento en la barra de menu

![IMG_2658](https://user-images.githubusercontent.com/61850215/82108243-cfc0ea00-96f2-11ea-916a-ccf86190b7cc.PNG)

- Apilamiento en las calculadoras

![Archivo 15-5-20 21 27 25](https://user-images.githubusercontent.com/61850215/82108266-fb43d480-96f2-11ea-9ec2-a13d742bd635.jpeg)

Vista en Safari iPhone6

- La tipografía del título Reconocimientos cambia, no es Montserrat

- Apilamiento en las calculadoras
