### ISSUE TITLE
INVERSIONISTA PR.2.0.1.Back: Usuario ve detalles de oportunidad de inversion (info-PUBLICA)

### ISSUE THREAD

**Issue by bram70** [bram70/viewflow-crece#9]
Este issue depende que se haya completado https://github.com/bram70/viewflow-crece/issues/7

Este issue es relacionado a ver mas detalles de la inversión a la que se interesa el inversionista potencial.
Dentro de los detalles a mostrar están los siguientes:

Como Usuario invitado, debo ser capaz de ver mas detalles de la oportunidad de inversion; para lo cual sere capaz de ver los siguientes nuevo detalles:
```
Nombre del solicitante
Categoría
Imagen
Sitio web
Descripción detallada del caso
Link que lleva a informe y resultado de análisis de la operación en PDF u otra pestaña en otra pantalla
TIR (tasa de retorno al inversionista)
Monto
Plazo
Historial de solicitudes (opción que se expande y muestra tabla resumida de las operaciones pasadas: fecha, estado, días de atraso)
% financiado
```
**ENDPOINT**
METHOD: GET
URL: solicitudes/ID_SOLICITUD
RESPONSE: 
```
{
   status: 200,
   solicitud: {
      id: 1234, (INTEGER, auto-increment)
      titulo: "Oportunidad de Inversion de XXXXX"", VARCHAR(200)
      operacion: "USD 2,100 para cubrir costos de materia prima y entrega del product" (TEXT)
      plazo:  61 (integer) "Numero de dias"
      autor: "Juan Piguave", (FK a Usuario-Solicitante)
      url: "www.juanpiguave.com" (TEXT)
      imagen_url: "aws.data.img/one.jpg", (TEXT)
      monto: "10.000", VARCHAR(10),
      moneda: "USD" , VARCHAR(10)
      tir: 15.0 FLOAT(4,2), "Porcentaje"
     categoria: "Agro" VARCHAR(100)
     tipo_credito: "CAPITAL DE TRABAJO", VARCHAR(100),
      fecha_creacion: "10-02-2020", (TIMESTAMP)
      fecha_publicacion: "15-02-2020", (TIMESTAMP)
      fecha_finalizacion: "10-03-2020", (TIMESTAMP) ,
      fecha_expiracion: "10-05-2020", (TIMESTAMP),
      porcentaje_financiado: 30.5 FLOAT(4,2) 
      }
}
```
**ESTA PARTE ES EN EL FRONTEND**
 Adicionalmente, en esta seccion tengo la habilidad de simular un poco con los valores que se muestran en esta seccion.
@fcobrionesr aqui se necesita completar la parte de la SIMULACION: ok

Se trata de poner dos cuadros de texto interactivos en la oración. Uno en el que se ingresa un valor y el otro que muestra un resultado a partir de ese valor.

Con las mismas fórmulas y cálculos que se están haciendo para la tabla de amortización se pueden calcular estos valores.

Los detalles técnicos lo podemos ver reunidos para poder explicar, pero si se hace la tabla de amortización esto es poner nomás que publique uno de esos valores.

**Comment by fcobrionesr** [comment]
No entiendo qué debo hacer en esta. Por favor dame una instrucción más puntual.

**Comment by bram70** [comment]
@fcobrionesr basicamente definir la parte inferior de la imagen que dibujaste.
![Image from iOS](https://user-images.githubusercontent.com/550702/76373956-cfc9f580-630f-11ea-98e2-5b8f6068c9e5.jpg)

**Comment by fcobrionesr** [comment]
Se trata de poner dos cuadros de texto interactivos en la oración. Uno en el que se ingresa un valor y el otro que muestra un resultado a partir de ese valor. 

Con las mismas fórmulas y cálculos que se están haciendo para la tabla de amortización se pueden calcular estos valores. 

Los detalles técnicos lo podemos ver reunidos para poder explicar, pero si se hace la tabla de amortización esto es poner nomás que publique uno de esos valores.
